### PR TITLE
Create empty commit at root

### PR DESCRIPTION
**Pull request by gfontenot**
When creating a new project, it's kinda nice to have an empty root
commit. That means you go into a repo that's fully set up, but you can
begin crafting small commits right away, without having to worry about
what the first commit should look like.

### CODE REVIEW

**Comment by gabebw** [comment]
Why make an empty commit instead of committing everything all at once? Or just staging without committing: `git add -A`

**Comment by gfontenot** [comment]
I debated that. I think you _could_ make a case that it's nice to be _able_ to craft smaller commits with bits of the setup process if you want?

I could go either way. I just think doing some kind of initial commit is useful.

**Comment by gabebw** [comment]
> I think you could make a case that it's nice to be able to craft smaller commits with bits of the setup process if you want?

Yeah, I see what you mean, but I think the setup should be good as-is -- any improvements should be separate commits. Empty commits are also Kind Of Weird, so I prefer `git commit -Am "Initial commit"`

**Comment by gfontenot** [comment]
:+1: updated the PR

**Comment by gabebw** [comment]
:+1:

**Pull request merged**
